*************** Script Started *****************
******* MODEL LOADED ***********
SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: DistilBertModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)
********************************
******************* load and slice data ********************
Lenght of train set 3121
len of dev_data 780
Traceback (most recent call last):
  File "/lustre06/project/6084435/ksjoe30/aied-cods-comad/src/training_constrastiveLoss.py", line 61, in <module>
    seq_evaluator(model, epoch=0, steps=0, output_path=output_path)
  File "/lustre06/project/6084435/ksjoe30/ubc/lib/python3.10/site-packages/sentence_transformers/evaluation/SequentialEvaluator.py", line 18, in __call__
    scores.append(evaluator(model, output_path, epoch, steps))
  File "/lustre06/project/6084435/ksjoe30/ubc/lib/python3.10/site-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 99, in __call__
    with open(csv_path, newline='', mode="w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../models/firstmodel/binary_classification_evaluation_results.csv'
